// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/navbar";
// //import Sidebar from "./components/sidebar";
// import Sidebar from "./components/sidebar-menu";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="th">

//       <body className={inter.className}>
//         {/* <Header /> */}
//         <header>
//           <div>
//             <Navbar />
//             <Sidebar />
//           </div>

//         </header>

//         {children}
//       </body>
//     </html>
//   );
// }
import '@/app/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/app/components/header';
import { HeaderMobileAdminManagement, HeaderMobileAdmin } from '@/app/components/header-mobile';
import MarginWidthWrapper from '@/app/components/margin-width-wrapper';
import PageWrapper from '@/app/components/page-wrapper';
import { SideNavAdminManagement, SideNavAdmin } from '@/app/components/sidebar';
import { cookies } from 'next/headers';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { getToken, } from "next-auth/jwt";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Test Web',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children, }: { children: React.ReactNode; }) {

    console.log("RootLayout");
    const cookieStore = cookies();
    const NEXT_LOCALE = cookieStore.get('NEXT_LOCALE')?.value;
    //const CHECK_LOGIN = false;
    const CHECK_LOGIN = true;
    const USER_RULE = "AdminManagement";
    //const USER_RULE = "Admin";
    const messages = await getMessages();
    //console.log(messages);

    const secret = "ddd";
    const token = await getToken({
        req: 'token',
        secret: secret,
        raw: true,
    });

    console.log(token);

    const checkRule = (rule: string) => {
        switch (rule) {
            case "AdminManagement": {
                return <SideNavAdminManagement />
            }
            case "Admin": {
                return <SideNavAdmin />
            }
            default: {
                console.log("do nothing")
            }
        }
    }

    const checkRuleMobile = (rule: string) => {
        switch (rule) {
            case "AdminManagement": {
                return <HeaderMobileAdminManagement />
            }
            case "Admin": {
                return <HeaderMobileAdmin />
            }
            default: {
                console.log("do nothing")
            }
        }
    }

    return (
        <html lang="th">

            <body className={`bg-white${inter.className}`}>
                <NextIntlClientProvider messages={messages}>

                    {CHECK_LOGIN == true ?
                        <div className="flex">
                            {checkRule(USER_RULE)!}
                            <main className="flex-1">
                                <MarginWidthWrapper>
                                    <Header />

                                    {checkRuleMobile(USER_RULE)!}
                                    <PageWrapper>{children}</PageWrapper>
                                </MarginWidthWrapper>
                            </main>
                        </div>

                        :

                        <div className="flex">
                            <main className="flex-1">
                                <PageWrapper>{children}</PageWrapper>
                            </main>
                        </div>
                    }

                </NextIntlClientProvider>
            </body>
        </html>
    );
}