// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/navbar";
// //import Sidebar from "./components/sidebar";
// import Sidebar from "./components/sidebar-menu";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="th">

//       <body className={inter.className}>
//         {/* <Header /> */}
//         <header>
//           <div>
//             <Navbar />
//             <Sidebar />
//           </div>

//         </header>

//         {children}
//       </body>
//     </html>
//   );
// }


import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/app/components/header';
import { HeaderMobileAdminManagement, HeaderMobileAdmin } from '@/app/components/header-mobile';
import MarginWidthWrapper from '@/app/components/margin-width-wrapper';
import PageWrapper from '@/app/components/page-wrapper';
import { SideNavAdminManagement, SideNavAdmin } from '@/app/components/sidebar';

import { cookies } from 'next/headers';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const inter = Inter({ subsets: ['latin'] });



export const metadata: Metadata = {
  title: 'Test Web',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, }: { children: React.ReactNode; }) {

  const cookieStore = cookies();
  const NEXT_LOCALE = cookieStore.get('NEXT_LOCALE')?.value;
  const messages = await getMessages();
  console.log(messages);
  return (
    <html lang="en">

      <body className={`bg-white${inter.className}`}>
        <NextIntlClientProvider messages={messages}>
          <div className="flex">
            {NEXT_LOCALE == "th" ? <SideNavAdminManagement /> : <SideNavAdmin />}
            <main className="flex-1">
              <MarginWidthWrapper>
                <Header />


                {NEXT_LOCALE == "th" ? <HeaderMobileAdminManagement /> : <HeaderMobileAdmin />}
                <PageWrapper>{children}</PageWrapper>
              </MarginWidthWrapper>
            </main>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}